# infrastructure/prometheus/prometheus.yml
# Prometheus configuration for Bio-Data Validation System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bio-validation'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load alert rules
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Bio-Data Validation API
  - job_name: 'bio-validation-api'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # Use service name from docker-compose
    # Alternative: Use container name if 'api' doesn't work
    # - targets: ['bio-validation-api:8000']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']