# infrastructure/prometheus/prometheus.yml
# Docker Compose version - uses service names instead of localhost

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bio-validation-monitor'
    environment: 'development'

# Load alert rules
rule_files:
  - 'alerts.yml'

# Alertmanager configuration (optional - uncomment when ready)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

scrape_configs:
  # Bio-Data Validation API (Docker service name)
  - job_name: 'bio-validation-api'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']  # Use Docker service name, not localhost
        labels:
          service: 'bio-validation'
          component: 'api'
  
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          component: 'monitoring'