# config/policy_config.yml
# Policy configuration for validation decisions

decision_matrix:
  # Thresholds for automated decisions
  critical_threshold: 1      # Any critical issues = reject
  error_threshold: 5         # 5+ errors = reject
  warning_threshold: 10      # 10+ warnings = conditional accept
  moderate_warning_threshold: 5  # 5+ warnings = conditional accept (allows 1-4 warnings to be accepted)

human_review_triggers:
  on_critical: true          # Always review critical issues
  error_count_threshold: 3   # Review if 3+ errors
  warning_count_threshold: 15  # Review if 15+ warnings
  confidence_threshold: 0.7  # Review if confidence < 70%
  on_novel_errors: true      # Review novel/unknown error types

policies:
  - id: POL_001
    name: "Critical Data Integrity"
    description: "Any critical integrity issues result in rejection"
    condition: "severity.critical > 0"
    action: "rejected"
    priority: 1
  
  - id: POL_002
    name: "High Error Rate"
    description: "High number of errors indicates systemic issues"
    condition: "severity.error >= 5"
    action: "rejected"
    priority: 2
  
  - id: POL_003
    name: "Moderate Issues"
    description: "Some issues present but data may be usable with caution"
    condition: "severity.warning >= 3 AND severity.error < 5"
    action: "conditional_accept"
    priority: 3
  
  - id: POL_004
    name: "Clean Data"
    description: "Minimal or no issues detected"
    condition: "severity.error == 0 AND severity.warning < 3"
    action: "accepted"
    priority: 4

validation_workflow:
  # Define which validators run in which order
  stages:
    - name: "schema"
      validators: ["schema_validator"]
      blocking: true  # Failure stops workflow
      
    - name: "rules"
      validators: ["rule_validator"]
      blocking: false
      
    - name: "biological"
      validators: ["bio_rules", "bio_lookups"]
      parallel: true
      blocking: false

# Decision rationale templates
decision_rationales:
  accepted: "All validation checks passed. No significant issues detected."
  conditional_accept: "Validation completed with {warning_count} warnings. Data may be used with caution. Review recommended for critical applications."
  rejected: "Validation failed with {error_count} errors and {critical_count} critical issues. Data quality is insufficient for use."
  review_required: "Human review required due to: {review_reasons}"