# config/validation_rules.yml
# Validation rules configuration for biological data validation

# 🆕 RULESET VERSION - Tracked in all validation reports
version: "1.2.0"
last_updated: "2025-10-17"
changelog:
  - version: "1.2.0"
    date: "2025-10-17"
    changes:
      - "Added gene symbol caching support"
      - "Added Ensembl fallback provider"
      - "Added variant annotation validation rules"
      - "Added sample metadata validation rules"
  - version: "1.1.0"
    date: "2025-10-09"
    changes:
      - "Added custom rule support"
      - "Enhanced bias detection"
  - version: "1.0.0"
    date: "2025-10-01"
    changes:
      - "Initial ruleset"

rules:
  consistency:
    # Required columns - empty by default for flexibility
    # Uncomment for guide_rna format:
    # required_columns:
    #   - guide_id
    #   - sequence
    #   - pam_sequence
    #   - target_gene
    #   - organism
    required_columns: []
    
    # Expected data types for columns (only check if present)
    # Uncomment to enable type checking:
    # column_types:
    #   guide_id: string
    #   sequence: string
    #   gc_content: float
    #   efficiency_score: float
    column_types: {}
    
    # Value range constraints (only check if column exists)
    value_ranges:
      gc_content:
        min: 0.0
        max: 1.0
      efficiency_score:
        min: 0.0
        max: 1.0
      on_target_score:
        min: 0.0
        max: 1.0
      off_target_score:
        min: 0.0
        max: 1.0
      # Add more as needed:
      # specificity_score:
      #   min: 0.0
      #   max: 1.0
    
    # Cross-column validation rules
    cross_column:
      - column1: end_position
        operator: ">"
        column2: start_position
      # Add more cross-column rules as needed:
      # - column1: on_target_score
      #   operator: ">"
      #   column2: off_target_score
  
  duplicates:
    # Check for duplicate rows
    check_duplicate_rows: true
    
    # Columns that must be unique (only if they exist)
    unique_columns:
      - guide_id
    
    # Columns to check for sequence duplicates
    sequence_columns:
      - sequence
    
    # Similarity threshold for near-duplicate sequences (0.0-1.0)
    # 0.95 = 95% similar (e.g., 1-2 mismatches in 20bp guide)
    sequence_similarity_threshold: 0.95
  
  bias:
    # Column containing class labels (null = don't check by default)
    # Set to column name to enable bias detection:
    # target_column: efficiency_category  # e.g., 'high', 'medium', 'low'
    target_column: null
    
    # Class imbalance threshold (minority class < this ratio)
    # 0.3 = minority class must be at least 30% of dataset
    imbalance_threshold: 0.3
    
    # Missing value threshold (missing > this ratio triggers warning)
    # 0.1 = warn if >10% of values are missing
    missing_value_threshold: 0.1
    
    # Columns to check for distribution bias (empty = none by default)
    # Uncomment to enable skewness checks:
    # check_distribution_bias:
    #   - efficiency_score
    #   - gc_content
    check_distribution_bias: []
  
  # Custom rules (uses pandas query syntax)
  # Examples:
  # custom:
  #   - id: CUSTOM_001
  #     field: sequence
  #     expression: "sequence.str.len() >= 18"
  #     message: "Sequence must be at least 18bp"
  #     severity: error
  #   
  #   - id: CUSTOM_002
  #     field: gc_content
  #     expression: "gc_content >= 0.4 and gc_content <= 0.7"
  #     message: "GC content should be between 40-70% for optimal efficiency"
  #     severity: warning
  custom: []

# =============================================================================
# USAGE EXAMPLES
# =============================================================================
# 
# Example 1: Strict guide RNA validation
# --------------------------------------
# rules:
#   consistency:
#     required_columns:
#       - guide_id
#       - sequence
#       - pam_sequence
#       - target_gene
#     value_ranges:
#       gc_content: {min: 0.4, max: 0.7}  # Optimal range
#   duplicates:
#     unique_columns: [guide_id]
#     sequence_similarity_threshold: 0.90  # Stricter
# 
# Example 2: Lenient exploratory analysis
# ----------------------------------------
# rules:
#   consistency:
#     required_columns: []  # No requirements
#   duplicates:
#     check_duplicate_rows: false  # Allow duplicates
#     sequence_similarity_threshold: 0.99  # Only flag near-identical
#   bias:
#     missing_value_threshold: 0.5  # Allow up to 50% missing
# 
# Example 3: Production ML pipeline
# ----------------------------------
# rules:
#   bias:
#     target_column: efficiency_category
#     imbalance_threshold: 0.25  # Stricter balance requirement
#     missing_value_threshold: 0.05  # Very strict
#     check_distribution_bias:
#       - efficiency_score
#       - gc_content
#       - on_target_score
# =============================================================================

# =============================================================================
# Variant Annotation Validation Rules
# =============================================================================
variant_validation:
  reference_genome: "GRCh38"  # or GRCh37, hg19, hg38
  
  required_columns:
    - chromosome
    - position
    - ref_allele
    - alt_allele
  
  optional_columns:
    - gene_symbol
    - consequence
    - hgvs_c
    - hgvs_p
    - gnomad_af
    - clinvar_significance
  
  chromosome_format:
    allow_chr_prefix: true
    standardize_to: "with_prefix"  # "with_prefix" or "without_prefix"
  
  allele_frequency_thresholds:
    common_variant: 0.01  # >1% = common
    rare_variant: 0.001   # <0.1% = rare
    
  consequence_terms:
    use_vep_standard: true
    custom_terms: []

# =============================================================================
# Sample Metadata Validation Rules
# =============================================================================
sample_metadata_validation:
  required_fields:
    - sample_id
    - organism
    - tissue_type
    - collection_date
  
  recommended_fields:
    - cell_type
    - treatment
    - time_point
    - replicate_id
    - batch_id
    - experimenter
  
  ontology_validation:
    require_ontologies: true  # Require ontology IDs vs free text
    tissue_ontology: "UBERON"
    cell_ontology: "CL"
    experiment_ontology: "EFO"
    chemical_ontology: "CHEBI"
  
  unit_validation:
    strict_units: true  # Require standardized units
    concentration_units: ["M", "mM", "uM", "nM"]
    time_units: ["s", "m", "h", "d"]
    temperature_units: ["C", "F", "K"]
    volume_units: ["L", "mL", "uL"]
  
  batch_effect_detection:
    check_batch_imbalance: true
    max_batch_size_ratio: 5.0  # Flag if batch sizes differ >5x
    check_confounding: true  # Check if batch confounded with condition
  
  date_format:
    require_iso8601: true  # YYYY-MM-DD format
  
  missing_data:
    max_missing_per_field: 0.3  # Warn if >30% missing