# Validation rules configuration

rules:
  consistency:
    # Required columns - make optional for guide_rna format
    required_columns: []
    
    # Expected data types for columns (only check if present)
    column_types: {}
    
    # Value range constraints (only check if column exists)
    value_ranges:
      gc_content:
        min: 0.0
        max: 1.0
      efficiency_score:
        min: 0.0
        max: 1.0
      on_target_score:
        min: 0.0
        max: 1.0
    
    # Cross-column validation rules
    cross_column:
      - column1: end_position
        operator: ">"
        column2: start_position
  
  duplicates:
    # Check for duplicate rows
    check_duplicate_rows: true
    
    # Columns that must be unique (only if they exist)
    unique_columns:
      - guide_id
    
    # Columns to check for sequence duplicates
    sequence_columns:
      - sequence
    
    # Similarity threshold for near-duplicate sequences
    sequence_similarity_threshold: 0.95
  
  bias:
    # Column containing class labels (null = don't check by default)
    target_column: null
    
    # Class imbalance threshold (minority class < this ratio)
    imbalance_threshold: 0.3
    
    # Missing value threshold (missing > this ratio triggers warning)
    missing_value_threshold: 0.1
    
    # Columns to check for distribution bias (empty = none by default)
    check_distribution_bias: []
  
  custom: []
